# Project information
site_name: What I learned today (@aclk)
site_description: '@aclk''s Personal Tech Docs'
site_author: 'Bunkei Ka'
site_url: 'https://blog.sbux.cf/'
fb_appid: '0000000000000'

# Page tree
nav:
  - Home: README.md
  - About Me: about.md
  - What's New: whats-new.md
  - Tools & Techniques:
    - A Dev VM in the sky: misc\cloud-dev-vms.md
    - Import Shapes into Draw.io: misc\shapes.md
    - Scoop & Co: misc\scoop.md
    - Bash Shell on Windows: misc\git-bash.md
    - About PowerShell Module Paths: misc\ps-module-paths.md
    - Miscellanous Notes: misc\misc.md
  - DevOps:
    - DevOps for the Terrified: devops\devops-for-the-terrified.md
    - Azure DevOps - Self-Hosted Build Agents: devops\azdo-self-hosted-build-agents.md
    - VM Patching in DevTest Labs: compute\patching-devtestlabs.md
  - Kubernetes:
    - Clusters and Domains: aks\domains.md
    - Create a TLS Secret: aks\create-tls-secret.md
  - Writing:
    - Prettier link sharing with MkDocs: writing\social-media-sharing.md
    - Technical Diagramming: writing\diagrams.md

# Repository
repo_name: 'aclk/notes'
repo_url: 'https://github.com/aclk/notes'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Bunkei Ka'

# Configuration
theme:
  name: material
  language: 'en'
  custom_dir: 'theme'
  palette:
    primary: 'deep purple'
    accent: 'green'
  font:
    text: 'Noto Sans'
    code: 'Ubuntu Mono'
  features:
    - tabs
    - instant
  icon:
    logo: material/library

# Plugins
plugins:
  - search:
      separator: '[\s\-\.]+'
  - git-revision-date
  - minify:
      minify_html: true

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/aclk'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/aqingo'
    - icon: fontawesome/brands/github
      link: 'https://github.com/aclk'
    - icon: fontawesome/brands/facebook
      link: 'https://fb.com/aqinge'
    - icon: fontawesome/brands/instagram
      link: 'https://www.instagram.com/vk.he/'
    - icon: fontawesome/solid/terminal
      link: 'https://asciinema.org/~aqing'
  disqus: 'aclk'
  theme:
    icon:
      repo: fontawesome/brands/gitlab

extra_javascript:
  - js/extra.js
  - 'https://platform.linkedin.com/badges/js/profile.js'

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - fontawesome_markdown
  - markdown.extensions.abbr
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.md_in_html
  - markdown.extensions.meta
  - markdown.extensions.tables
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      hide_protocol: true
      social_url_shortener: true
      social_url_shorthand: true
      provider: github
      user: aclk
      repo: notes
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs/_snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
